config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: 'custom/registrations' }, skip: [ :sessions ]
  as :user do
    get 'entrar' => "devise/sessions#new", as: :new_user_session
    post 'signin' => 'devise/sessions#create', as: :user_session
    delete 'sair' => 'devise/sessions#destroy', as: :destroy_user_session
  end

  scope(path_names: { new: 'novo', edit: 'editar' }) do
    resources :users, except: [ :create ], path: '/usuarios'
    resources :events, path: '/eventos' do
      get 'inscritos', on: :member, action: :registrations, as: :registrations
      patch :import, on: :member
      get :lista, on: :member, action: :printer, as: :printer
    end
    resources :locals, path: '/estabelecimentos'
    resources :rooms, path: '/salas'
    resources :groups, path: '/grupos'
    resources :customers, path: '/clientes'
    resources :managers, only: :destroy
    resources :participants, path: '/participantes'
    resources :registrations, only: :destroy do
      post :confirm, on: :collection
    end
  end

  get "events", to: "dashboard#index", format: true

  root to: "dashboard#index"
end

app/models/event.rb
class Event < ActiveRecord::Base
  default_scope { order(start_at: :desc) }

  belongs_to :customer
  belongs_to :local
  has_many :rooms
  has_many :registrations
  has_many :participants, through: :registrations

  mount_uploader :sheet, SheetUploader

  delegate :address, :number, :cep, :neighborhood, :city, :state, to: :local

  KINDA = [
    [ 'Workshop', 'Workshop'],
    [ 'Seminário', 'Seminário'],
    [ 'Conferência', 'Conferência'],
    [ 'Palestras', 'Palestras'],
    [ 'Convenção', 'Convenção'],
    [ 'Evento Social', 'Evento Social'],
    [ 'Evento Corporativo', 'Evento Corporativo'],
    [ 'Lançamento', 'Lançamento']
  ]

  validates :name, :start_at, :ends_at, :local_id, :customer_id, presence: true

  accepts_nested_attributes_for :rooms

  scope :in_coming, -> { where("ends_at >= ?", Time.zone.now) }

  def to_param
    "#{self.id}-#{self.name.parameterize}"
  end

  def is_current?
    (self.start_at.past? || self.start_at.today?) && self.ends_at.future?
  end

  def past?
    self.ends_at.past?
  end

end

app/controllers/events_controller.rb
class EventsController < InheritedResources::Base
  before_action :authenticate_user!
  before_action :denied!

  def registrations
    # Sorry about this
    @cities = resource.registrations.ordered.pluck("participants.city").uniq
    @registrations = resource.registrations.ordered.includes(:participant)
    if params[:cidade] && !params[:cidade].blank?
      @registrations = @registrations.where("participants.city = ?", params[:cidade])
    end
    if params[:confirmados] == "on"
      @registrations = @registrations.confirmed
    end
    if params[:nome] && !params[:nome].blank?
      @registrations = @registrations.where("participants.name LIKE ?", "%#{params[:nome]}%")
    end
    @registrations = @registrations.paginate(page: params[:pagina])
  end

  def import
    resource.sheet = params[:event][:sheet]
    resource.save!
    redirect_to registrations_event_path(resource), notice: 'Processando arquivo...'
  end

  def printer
    @registrations = resource.registrations.confirmed.ordered
    respond_to do |format|
      format.html { render layout: 'printer' }
      format.csv do
        headers['Content-Disposition'] = "attachment; filename=\"lista-#{resource.name.parameterize}\""
        headers['Content-Type'] ||= 'text/csv'
      end
    end
  end

  private

    def collection
      get_collection_ivar || set_collection_ivar(end_of_association_chain.paginate(page: params[:pagina]))
    end

    def event_params
      params.require(:event).permit(:name, :customer_id, :kind, :local_id, :start_at, :ends_at, :manager, :max_clients, :montage_date, :montage_ends, :observations, :internals, :phone, :sheet,
        rooms_attributes: [ :name, :max_capacity, :min_capacity ])
    end

end

app/helpers/events_helper.rb
module EventsHelper

  def is_current? start_at, ends_at
    (start_at.past? || start_at.today?) && ends_at.future?
  end

end

app/views/events/_form.html.erb
<div class="column-left">
  <p><%= f.label :customer, 'Cliente' %><br />
  <%= f.select :customer_id, Customer.all.collect{ |customer| [customer.name, customer.id] }, { include_blank: true } %></p>

  <p><%= f.label :name, 'Nome do Evento' %><br />
  <%= f.text_field :name, placeholder: 'Nome', required: true %></p>

  <p><%= f.label :kind, 'Tipo de Evento' %><br />
  <%= f.select :kind, Event::KINDA.map{|k|[k[1], k[0]]} %></p>

  <p><%= f.label :manager, 'Coordenador' %><br />
  <%= f.text_field :manager, placeholder: 'Nome da Gerência' %></p>

  <div class="combined">
    <p class="medium"><%= f.label :start_at, 'Data de Início' %><br />
    <%= f.text_field :start_at, class: 'datepicker', value: datetime_for(@event.start_at) %> <span class="icon calendar"></span></p>
    <p class="medium"><%= f.label :ends_at, 'Data de Término' %><br />
    <%= f.text_field :ends_at, class: 'datepicker', value: datetime_for(@event.ends_at) %> <span class="icon calendar"></span></p>
  </div>

  <p><%= f.label :max_clients, 'Máximo de Participantes' %><br />
  <%= f.text_field :max_clients %></p>
</div>

<div class="column-right">
  <p><%= f.label :local_name, 'Local do Evento' %><br />
  <%= f.select :local_id, Local.all.collect{ |local| [local.name, local.id] }, { include_blank: true, required: true } %></p>

  <p><%= f.label :phone, 'Telefone para Contato' %><br />
  <%= f.text_field :phone, placeholder: 'Telefone' %></p>

  <div class="combined">
    <p class="medium"><%= f.label :montage_date, 'Início da Montagem' %><br />
    <%= f.text_field :montage_date, class: 'datepicker', value: datetime_for(@event.montage_date) %> <span class="icon calendar"></span></p>

    <p class="medium"><%= f.label :montage_ends, 'Final da Montagem' %><br />
    <%= f.text_field :montage_ends, class: 'datepicker', value: datetime_for(@event.montage_ends) %> <span class="icon calendar"></span></p>
  </div>

  <p><%= f.label :observations, 'Observações' %><br />
  <%= f.text_area :observations, placeholder: 'Observações' %></p>

  <p><%= f.label :internals, 'Informações Internas' %><br />
  <%= f.text_area :internals, placeholder: 'Observações Internas' %></p>

</div>


<div class="clear"></div>

<div class="action_bar">
  <%= f.submit "Salvar", class: "button blue" %>
  <a href="/">Cancelar</a>
</div>

app/views/events/_room_fields.html.erb
<div class="fields">
  <div class="combined">
    <p class="medium"><%= f.label :name, 'Nome da Sala' %><br />
    <%= f.text_field :name, placeholder: 'Nome', required: true %></p>
    <p class="small"><%= f.label :max_capacity, 'Cap. Máxima', required: true %><br />
    <%= f.text_field :max_capacity %></p>
    <p class="small"><%= f.label :min_capacity, 'Cap. Mínima', required: true %><br />
    <%= f.text_field :min_capacity %> </p>
  </div>
</div>

<div class="clear"></div>

<div class="action_bar">
  <%= f.submit "Salvar Sala", class: "button blue" %>
</div>

app/views/events/edit.html.erb
<div class="box">
  <div class="box-header">
    <h1>Eventos</h1>
  </div>
  <div class="box-content">
    <%= form_for(@event) do |f| %>
      <%= render partial: 'form', locals: { f: f } %>
    <% end %>
  </div>
</div>

app/views/events/index.html.erb
  <div class="box">
    <div class="box-header">
      <h1>Eventos</h1>
    </div>

    <% if @events.any? %>

    <table>
      <thead>
        <tr>
          <th>Cliente</th>
          <th>Nome</th>
          <th>Data de Início</th>
          <th>Local</th>
          <th>Cidade</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @events.all.each do |event| %>
        <tr>
          <td><%= event.customer.try(:name) %></td>
          <td><%= event.name %></td>
          <td><%= datetime_for event.start_at %></td>
          <td><%= event.local.try(:name) %></td>
          <td><%= event.city %>/<%= event.state %></td>
          <td>
            <%= link_to 'Detalhes', event_path(event), class: "button plain" %>
            <%= link_to 'Editar', edit_event_path(event), class: "button plain" %>
            <%= link_to 'Participantes', registrations_event_path(event), class: "button plain" %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>

    <% else %>
      <div class="box-content">
        <p>Nenhum evento. <%= link_to 'Adicionar Evento', new_event_path, class: 'button small plain' %></p>
      </div>
    <% end %>

    <%= render partial: 'commons/pagination', locals: { paginated_collection: @events } %>
  </div>

app/views/events/new.html.erb
<div class="box">
  <div class="box-header">
    <h1>Eventos</h1>
  </div>
  <div class="box-content">
    <%= form_for(@event) do |f| %>
      <%= render partial: 'form', locals: { f: f } %>
    <% end %>
  </div>
</div>

app/views/events/printer.csv.erb
<%= CSV.generate_line ['Setor', 'Responsável', 'Nome', 'CNO', 'Cidade', 'Estado'] -%>

<%- @registrations.each do |registration| -%>
  <%= CSV.generate_line([registration.group.name, registration.group.manager, registration.name, registration.cno_code, registration.city, registration.state]).html_safe -%>
<%- end -%>

app/views/events/printer.html.erb
  <table class="table table-bordered">

    <tbody>
      <tr>
        <td colspan="2" style="text-align:center"><h2><%= link_to resource.name, event_path(resource) %></h2></td>
      </tr>

      <tr>
        <td><b>Local</b></td>
        <td><%= resource.local.name %></td>
      </tr>

      <tr>
        <td><b>Início</b></td>
        <td><%= datetime_for resource.start_at %></td>
      </tr>

      <tr>
        <td><b>Término</b></td>
        <td><%= datetime_for resource.ends_at %></td>
      </tr>

      <tr>
        <td><b>Participantes Confirmados</b></td>
        <td><%= @registrations.size %></td>
      </tr>
    </tbody>

  </table>

  <% if @registrations.any? %>
    <table class="table table-striped table-bordered">
      <thead>
        <tr>
          <th>Setor</th>
          <th>Responsável</th>
          <th>Nome</th>
          <th>CNO</th>
          <th>Cidade/Estado</th>
        </tr>
      </thead>

      <tbody>
        <% @registrations.each do |registration| %>
          <tr>
            <td><%= registration.group.name %></td>
            <td><%= registration.group.manager %></td>
            <td><%= registration.name %></td>
            <td><%= registration.cno_code %></td>
            <td><%= registration.city %>/<%= registration.state%></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <div class="panel">
      <p>Nenhum inscrito.</p>
    </div>
  <% end %>
  

app/views/events/registrations.html.erb
<%= image_tag 'loader.gif', class: 'pull-right loader', style: 'display:none' %>

<div class="box">
  <div class="box-header">
    <h1>Inscrições</h1>
  </div>
  <div class="box-content">
    <%= form_tag 'inscritos', method: :get do %>
      <div class="column-left">
        <p><label>Busca Por Nome</label><br />
        <%= text_field_tag "nome", params[:nome] %></p>
      </div>
      <div class="column-right">
        <div class="combined">
          <p class="medium"><label>Filtrar por Cidade</label><br />
          <%= select_tag "cidade", options_for_select(@cities, params[:cidade]), include_blank: true %></p>
          <p class="small"><label>Confirmados</label><br />
          <%= check_box_tag "confirmados", params[:confirmados], params[:confirmados] %></p>
        </div>
      </div>
      <div class="clear"></div>

      <div class="action_bar">
        <%= submit_tag "Filtrar", class: "button blue" %>
      </div>

    <% end %>
  </div>
</div>

<div class="box">
  <div class="box-header">
    <h1><%= resource.name %></h1>
    <%= link_to "Imprimir Confirmados", printer_event_path(resource), class: "button plain pull-right" %>
    <%= link_to 'Download CSV', printer_event_path(resource, format: :csv), class: 'button plain pull-right' %>
    <%= link_to event_path(resource), class: "button plain pull-right" do %>
      <span class="ui-icon ui-icon-carat-1-w"></span>Voltar ao Evento
    <% end %>
  </div>

  <% if @registrations.any? %>
    <table>
      <thead>
        <tr>
          <th>Nome</th>
          <th>Setor</th>
          <th>Cidade/Estado</th>
          <th>Confirmado?</th>
          <% if resource.past? %>
            <th>Compareceu?</th>
          <% end %>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <% @registrations.each do |registration| %>
          <tr>
            <td><%= registration.name %></td>
            <td><%= registration.group.name %></td>
            <td><%= registration.city %>/<%= registration.state%></td>
            <td><%= check_box_tag "confirm", registration.confirm?, registration.confirm?, class: "js-switch toggle", data: { id: registration.id } %> </td>

            <% if resource.past? %>
              <td><%= check_box_tag "presence", registration.presence?, registration.presence?, class: "js-switch toggle", data: { id: registration.id } %> </td>
            <% end %>

            <td>
              <%= link_to 'Detalhes', participant_path(registration.participant), class: "button plain" %>
              <%= link_to 'Remover', registration_path(registration), class: "button plain", method: :delete, data: { confirm: 'Tem Certeza? ' } %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <div class="box-content">
      <p>Nenhum inscrito.</p>
    </div>
  <% end %>

  <%= render partial: 'commons/pagination', locals: { paginated_collection: @registrations } %>
</div>

<% content_for :javascript do %>
  <script type="text/javascript">
    var elems = Array.prototype.slice.call(document.querySelectorAll('input[type=checkbox]'));
    elems.forEach(function(html) {
      var switchery = new Switchery(html, { size: 'small' });
    });

    jQuery('.toggle').on('change', function(){
      jQuery.post( "/registrations/confirm", { id: this.getAttribute('data-id'), field: this.getAttribute('id') });
    });

    if(jQuery('.notice').text().trim() == "Processando arquivo...") {
      jQuery('.loader').show()
      stream = setInterval(function(){
        jQuery('.notification').text('Isso pode levar alguns minutos...').removeClass('notice').addClass('error');
        clearTimeout(stream);
      }, 5000);
      setInterval(function(){
        location.reload();
      }, 8000);
    }
  </script>
<% end %>

app/views/events/show.html.erb
<div class="box grid_6 alpha">

  <div class="box-header">
    <h1>Evento</h1>
  </div>

  <table>
    <tbody>
      <tr>
        <td>Nome</td>
        <td><strong><%= @event.name %></strong></td>
      </tr>

      <tr>
        <td>Cliente</td>
        <td><strong><%= link_to_if @event.customer, @event.customer.try(:name), customer_path(@event.customer) %></strong></td>
      </tr>

      <tr>
        <td>Tipo</td>
        <td><%= @event.try(:kind) %></td>
      </tr>
      <tr>
        <td>Gerente</td>
        <td><%= @event.manager %></td>
      </tr>

      <tr>
        <td>Início</td>
        <td><%= datetime_for @event.start_at %></td>
      </tr>

      <tr>
        <td>Término</td>
        <td><%= datetime_for @event.ends_at %></td>
      </tr>

      <tr>
        <td>Máximo de Participantes</td>
        <td><%= @event.max_clients %></td>
      </tr>

      <tr>
        <td>Local do Evento</td>
        <td><%= @event.local.try(:name) %></td>
      </tr>

      <tr>
        <td>Endereço</td>
        <td><%= @event.local.try(:address) %> <%= @event.local.try(:number) %></td>
      </tr>
      <tr>
        <td>Cidade/Estado</td>
        <td><%= @event.local.try(:city) %>/<%= @event.local.try(:state) %></td>
      </tr>
      <tr>
        <td>Telefone</td>
        <td><%= @event.phone %></td>
      </tr>

      <tr>
        <td>Início da Montagem</td>
        <td><%= datetime_for @event.montage_date %></td>
      </tr>

      <tr>
        <td>Término da Montagem</td>
        <td><%= datetime_for @event.montage_ends %></td>
      </tr>

      <tr>
        <td colspan="2">Observações</td>
      </tr>

      <tr><td colspan="2"><blockquote><%= @event.observations %></blockquote></td></tr>

      <tr>
        <td colspan="2">Informações Internas</td>
      </tr>

      <tr><td colspan="2"><blockquote><%= @event.internals %></blockquote></td></tr>
    </tbody>
  </table>

  <div class="action_bar">
    <%= link_to 'Editar', edit_event_path(@event), class: 'button plain' %>
    <%= link_to 'Remover', event_path(@event), class: "button plain", method: :delete, data: { confirm: 'TEm Certeza? ' } %>
  </div>

</div>

<!-- Registrations -->
<div class="box grid_6 omega">
  <div class="box-header">
    <h1>Participantes</h1>
  </div>
  <table>
    <tbody>
      <tr>
        <td>Total de Inscritos</td>
        <td><strong><%= @event.registrations.size %></strong></td>
      </tr>

      <tr>
        <td>Confirmados</td>
        <td><strong><%= @event.registrations.confirmed.size %></strong></td>
      </tr>

      <tr>
        <td>Compareceram</td>
        <td><strong><%= @event.registrations.present.size %></strong></td>
      </tr>
    </tbody>
  </table>

  <div class="action_bar">
    <%= link_to 'Lista de Participantes', registrations_event_path(@event), class: 'button plain' %>
    <%= link_to 'Imprimir Confirmados', printer_event_path(@event), class: 'button plain' %>
    <%= link_to 'Download CSV', printer_event_path(@event, format: :csv), class: 'button plain' %>
  </div>

</div>

<!-- Rooms -->
<div class="box grid_6 omega">
  <div class="box-header">
    <h1>Salas deste Evento</h1>
  </div>

  <% if @event.rooms.any? %>

    <table>
      <thead>
        <tr>
          <th>Nome</th>
          <th>Capacidade</th>
          <th>Alocados</th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <% @event.rooms.each do |room| %>
          <tr>
            <td><%= room.name %></td>
            <td><%= room.max_capacity %></td>
            <td></td>
            <td>
              <%= link_to 'Ver', room_path(room), class: "button plain" %>
              <%= link_to 'Remover', room_path(room), class: "button plain", method: :delete, data: { confirm: 'Tem Certeza? ' } %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>

  <% else %>
    <div class="box-content">
      <p>Nenhuma sala cadastrada. Utilize o formulário abaixo para cadastrar.</p>
    </div>
  <% end %>
</div>

<div class="box grid_6 omega">
  <div class="box-header">
    <h1>Adicionar Sala para este evento</h1>
  </div>

  <div class="box-content">
    <%= form_for(@event) do |f| %>
      <% f.fields_for :rooms, Room.new do |r| %>
        <%= render partial: 'room_fields', locals: { f: r } %>
      <% end %>
    <% end %>
  </div>
</div>

<div class="box grid_6 omega">
  <div class="box-header">
    <h1>Importar lista de inscritos</h1>
  </div>
  <div class="box-content">
    <%= form_for @event, url: { action: :import }, html: { multipart: true } do |f| %>
      <p>Selecione um arquivo no formato XLSX contendo os campos de participantes.<br />
      <%= f.hidden_field :sheet_cache %>
      <%= f.file_field :sheet, required: true, value: nil %></p>

      <div class="action_bar">
        <%= f.submit "Importar", class: "button blue" %>
        <a href="/">Cancelar</a>
      </div>
    <% end %>
  </div>
</div>