config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: 'custom/registrations' }, skip: [ :sessions ]
  as :user do
    get 'entrar' => "devise/sessions#new", as: :new_user_session
    post 'signin' => 'devise/sessions#create', as: :user_session
    delete 'sair' => 'devise/sessions#destroy', as: :destroy_user_session
  end

  scope(path_names: { new: 'novo', edit: 'editar' }) do
    resources :users, except: [ :create ], path: '/usuarios'
    resources :events, path: '/eventos' do
      get 'inscritos', on: :member, action: :registrations, as: :registrations
      patch :import, on: :member
      get :lista, on: :member, action: :printer, as: :printer
    end
    resources :locals, path: '/estabelecimentos'
    resources :rooms, path: '/salas'
    resources :groups, path: '/grupos'
    resources :customers, path: '/clientes'
    resources :managers, only: :destroy
    resources :participants, path: '/participantes'
    resources :registrations, only: :destroy do
      post :confirm, on: :collection
    end
  end

  get "events", to: "dashboard#index", format: true

  root to: "dashboard#index"
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  validates :name, :city, :state, presence: true
  has_many :events
  has_many :managers
  accepts_nested_attributes_for :managers
end

app/controllers/customers_controller.rb
class CustomersController < InheritedResources::Base
  before_action :authenticate_user!
  before_action :denied!

  private

    def collection
      get_collection_ivar || set_collection_ivar(end_of_association_chain.paginate(page: params[:pagina]))
    end

    def customer_params
      params.require(:customer).permit(:name, :city, :state, managers_attributes: [ :name ])
    end
end

app/views/customers/_form.html.erb
<%= form_for(@customer) do |f| %>
  <p><%= f.label :name, 'Nome do Cliente' %><br />
  <%= f.text_field :name, required: true %></p>

  <div class="combined">
    <p class="large"><%= f.label :city, "Cidade" %><br><%= f.text_field :city, required: true %></p>
    <p class="minor"><%= f.label :state, "Estado" %><br>
      <%= f.select :state, ApplicationHelper::STATES.collect{ |state| [state, state] }, selected: 'RN' %></p>
  </div>

  <div class="action_bar">
    <%= f.submit "Salvar", class: "button blue" %>
    <a href="/">Cancelar</a>
  </div>
<% end %>

app/views/customers/_manager_fields.html.erb
<div class="fields">
  <p><%= f.label :name, 'Nome da Gerência' %><br />
  <%= f.text_field :name, required: true %></p>
</div>

<div class="clear"></div>

<div class="action_bar">
  <%= f.submit "Salvar Gerência", class: "button blue" %>
</div>

app/views/customers/edit.html.erb
<div class="box grid_6 alpha">
  <div class="box-header">
    <h1>Cliente</h1>
  </div>
  <div class="box-content">
    <%= render 'form' %>
  </div>
</div>

app/views/customers/index.html.erb
<div class="box">
  <div class="box-header">
    <h1>Clientes</h1>
  </div>

  <% if @customers.any? %>
    <table>
      <thead>
        <tr>
          <th>Nome</th>
          <th>Cidade</th>
          <th>Eventos</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @customers.each do |customer| %>
          <tr>
            <td><%= customer.name %></td>
            <td><%= customer.city %>/<%= customer.state %></td>
            <td><%= customer.events.size %></td>

            <td>
              <%= link_to 'Detalhes', customer_path(customer), class: "button plain" %>
              <%= link_to 'Editar', edit_customer_path(customer), class: "button plain" %>
              <%= link_to 'Remover', customer_path(customer), class: "button plain", method: :delete, data: { confirm: 'Tem Certeza? ' } %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>

  <% else %>
    <div class="box-content">
      <p>Nenhum cliente cadastrado. <%= link_to 'Adicionar Cliente', new_customer_path, class: 'button small plain' %></p>
    </div>
  <% end %>

  <%= render partial: 'commons/pagination', locals: { paginated_collection:  @customers } %>
</div>

app/views/customers/new.html.erb
<div class="box grid_6 alpha">
  <div class="box-header">
    <h1>Novo Cliente</h1>
  </div>
  <div class="box-content">
    <%= render 'form' %>
  </div>
</div>

app/views/customers/show.html.erb
<div class="grid_6 alpha">

  <div class="box">
    <div class="box-header">
      <h1>Cliente</h1>
    </div>

    <table>
      <tbody>
        <tr>
          <td>Nome</td>
          <td><%= @customer.name %></td>
        </tr>
        <tr>
          <td>Cidade</td>
          <td><%= @customer.city %>/<%= @customer.state %></td>
        </tr>
      </tbody>
    </table>

    <div class="action_bar">
      <%= link_to 'Editar', edit_customer_path(@customer), class: 'button plain' %>
    </div>
  </div>

  <div class="box">

    <div class="box-header">
      <h1>Eventos deste Cliente</h1>
    </div>

    <% if @customer.events.any? %>

      <table>
        <thead>
          <tr>
            <th>Nome</th>
            <th>Data</th>
            <th>Cidade</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @customer.events.each do |event| %>
            <tr>
              <td><%= event.name %></td>
              <td><%= datetime_for event.start_at %></td>
              <td><%= event.city %>/<%= event.state %></td>
              <td>
                <%= link_to 'Ver', event_path(event), class: "button plain" %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>

    <% else %>
      <div class="box-content">
        <p>Nenhum evento cadastrado. <%= link_to 'Adicionar Evento', new_event_path, class: 'button small plain' %></p>
      </div>
    <% end %>

  </div>

</div>


<div class="box grid_6 omega">

  <div class="box-header">
    <h1>Gerências</h1>
  </div>

  <% if @customer.managers.any? %>

    <table>
      <thead>
          <tr>
            <th>Código</th>
            <th>Nome</th>
            <th></th>
          </tr>
        </thead>
      <tbody>
        <% @customer.managers.each do |manager| %>
          <tr>
            <td><%= manager.id %></td>
            <td><%= manager.name %></td>
            <td>
              <%= link_to 'Remover', manager_path(manager), class: "button plain", method: :delete, data: { confirm: 'Tem Certeza? ' } %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>

  <% else %>
    <div class="box-content">
      <p>Nenhuma gerência cadastrada. Utilize o formulário abaixo para cadastrar.</p>
    </div>
  <% end %>

</div>

<div class="box grid_6 omega">

  <div class="box-header">
    <h1>Adicionar Gerências para este cliente</h1>
  </div>

  <div class="box-content">
    <%= form_for(@customer) do |f| %>
      <% f.fields_for :managers, Manager.new do |manager| %>
        <%= render partial: 'manager_fields', locals: { f: manager } %>
      <% end %>
    <% end %>
  </div>

</div>