config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: 'custom/registrations' }, skip: [ :sessions ]
  as :user do
    get 'entrar' => "devise/sessions#new", as: :new_user_session
    post 'signin' => 'devise/sessions#create', as: :user_session
    delete 'sair' => 'devise/sessions#destroy', as: :destroy_user_session
  end

  scope(path_names: { new: 'novo', edit: 'editar' }) do
    resources :users, except: [ :create ], path: '/usuarios'
    resources :events, path: '/eventos' do
      get 'inscritos', on: :member, action: :registrations, as: :registrations
      patch :import, on: :member
      get :lista, on: :member, action: :printer, as: :printer
    end
    resources :locals, path: '/estabelecimentos'
    resources :rooms, path: '/salas'
    resources :groups, path: '/grupos'
    resources :customers, path: '/clientes'
    resources :managers, only: :destroy
    resources :participants, path: '/participantes'
    resources :registrations, only: :destroy do
      post :confirm, on: :collection
    end
  end

  get "events", to: "dashboard#index", format: true

  root to: "dashboard#index"
end

app/views/commons/_flash.html.erb
<% flash.each do |name, msg| -%>
  <div class="notification <%= name %>">
    <span class="icon"></span> <%= msg %>
  </div>
<% end -%>

app/views/commons/_head.html.erb
<meta charset="utf-8">
<meta name="copyright" content="Fabrica2">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="apple-mobile-web-app-capable" content="yes" />
<meta name="apple-mobile-web-app-status-bar-style" content="black" />
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<%= yield :metatags %>
<meta property="og:locale" content="pt_BR">
<meta property="og:site_name" content="Fabrica2">
<meta property="og:type" content="website">
<meta property="fb:app_id" content="">

<title><%= yield(:title) %> Fabrica2</title>

<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
<%= yield :stylesheets %>

<link rel="canonical" href="<%= request.path %>">
<link rel="apple-touch-icon" href="apple-touch-icon-precomposed.png" />
<link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
<link rel="icon" href="/favicon.ico" type="image/x-icon">

<!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
  <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
<![endif]-->

<%= csrf_meta_tag %>

app/views/commons/_menu.html.erb
<nav id="primary">
  <ul>
    <li class="active">
      <%= link_to root_path do %>
        <span class="icon32 dashboard"></span>
        Painel
      <% end %>
    </li>
    <li>
      <%= link_to events_path do %>
        <span class="icon32 calendar"></span>
        Eventos
      <% end %>
    </li>
    <li>
      <%= link_to customers_path do %>
        <span class="icon32 listicon"></span>
        Clientes
      <% end %>
    </li>
    <li>
      <%= link_to edit_user_registration_path do %>
        <span class="icon32 tools"></span>
        Minha Conta
      <% end %>
    </li>
    <% if current_user.is_god? %>
    <li>
      <%= link_to users_path do %>
        <span class="icon32 user"></span>
        Usuários
      <% end %>
    </li>
    <% end %>
    <li class="bottom">
      <%= link_to destroy_user_session_path, method: :delete do %>
        <span class="icon32 quit"></span>
        Sair
      <% end %>
      </a>
    </li>
  </ul>
</nav>

app/views/commons/_nav_customers.html.erb
<ul>
  <li>Clientes &rarr;</li>
  <li><%= link_to 'Todos os Clientes', customers_path %></li>
  <li><%= link_to 'Adicionar Cliente', new_customer_path %></li>

  <li>Estabelecimentos &rarr;</li>
  <li><%= link_to 'Todos os Locais', locals_path %></li>
  <li><%= link_to 'Adicionar Local', new_local_path %></li>

  <li>Participantes &rarr;</li>
  <li><%= link_to 'Todos os Participantes', participants_path %></li>
  <li><%= link_to 'Adicionar Participante', new_participant_path %></li>
</ul>

app/views/commons/_nav_events.html.erb
<ul>
  <li>Eventos &rarr;</li>
  <li><%= link_to 'Todos os Eventos', events_path %></li>
  <li><%= link_to 'Adicionar Evento', new_event_path %></li>
  <li>Salas &rarr;</li>
  <li><%= link_to 'Todas as Salas', rooms_path %></li>
  <li><%= link_to 'Adicionar Sala', new_room_path %></li>
  <li>Grupos &rarr;</li>
  <li><%= link_to 'Todos os Grupos', groups_path %></li>
  <li><%= link_to 'Adicionar Grupo', new_group_path %></li>
</ul>

app/views/commons/_nav_users.html.erb
<ul>
  <li>Usuários &rarr;</li>
  <li><%= link_to 'Todos os Usuário', users_path %></li>
  <li><%= link_to 'Adicionar Usuário', new_user_path %></li>
</ul>

app/views/commons/_pagination.html.erb
<div class="action_bar nomargin">
  <div class="dataTables_info"><%= page_entries_info paginated_collection %></div>
  <%= will_paginate paginated_collection, param_name: :pagina, class: 'dataTables_paginate paging_full_numbers' %>
</div>