config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: 'custom/registrations' }, skip: [ :sessions ]
  as :user do
    get 'entrar' => "devise/sessions#new", as: :new_user_session
    post 'signin' => 'devise/sessions#create', as: :user_session
    delete 'sair' => 'devise/sessions#destroy', as: :destroy_user_session
  end

  scope(path_names: { new: 'novo', edit: 'editar' }) do
    resources :users, except: [ :create ], path: '/usuarios'
    resources :events, path: '/eventos' do
      get 'inscritos', on: :member, action: :registrations, as: :registrations
      patch :import, on: :member
      get :lista, on: :member, action: :printer, as: :printer
    end
    resources :locals, path: '/estabelecimentos'
    resources :rooms, path: '/salas'
    resources :groups, path: '/grupos'
    resources :customers, path: '/clientes'
    resources :managers, only: :destroy
    resources :participants, path: '/participantes'
    resources :registrations, only: :destroy do
      post :confirm, on: :collection
    end
  end

  get "events", to: "dashboard#index", format: true

  root to: "dashboard#index"
end

app/models/room.rb
class Room < ActiveRecord::Base
  validates :name, :event_id, :max_capacity, presence: true
  belongs_to :event
end

app/controllers/rooms_controller.rb
class RoomsController < InheritedResources::Base
  before_action :authenticate_user!
  before_action :denied!

  def destroy
    super do |format|
      format.html { redirect_to :back, notice: 'Sala removida!' }
    end
  end

  private
  
    def collection
      get_collection_ivar || set_collection_ivar(end_of_association_chain.paginate(page: params[:pagina]))
    end

    def room_params
      params.require(:room).permit(:name, :event_id, :max_capacity, :min_capacity, :observations)
    end
end

app/views/rooms/_form.html.erb
<div class="column-left">
  <p><%= f.label :event_id, 'Evento' %><br />
  <%= f.select :event_id, Event.all.map{|event|[event.name, event.id]} %></p>

  <p><%= f.label :name, 'Nome da Sala' %><br />
  <%= f.text_field :name, placeholder: 'Nome' %></p>

  <div class="combined">
    <p class="medium"><%= f.label :max_capacity, 'Capacidade Máxima' %><br />
    <%= f.text_field :max_capacity %></p>
    <p class="medium"><%= f.label :min_capacity, 'Capacidade Mínima' %><br />
    <%= f.text_field :min_capacity %> </p>
  </div>

</div>

<div class="column-right">
  <p>
    <%= f.label :observations, "Observações" %><br>
    <%= f.text_area :observations %>
  </p>
</div>

<div class="clear"></div>

<div class="action_bar">
  <%= f.submit "Salvar", class: "button blue" %>
  <a href="/">Cancelar</a>
</div>

app/views/rooms/edit.html.erb
<div class="box">
  <div class="box-header">
    <h1>Salas</h1>
  </div>
  <div class="box-content">
    <%= form_for(@room) do |f| %>
      <%= render partial: 'form', locals: { f: f } %>
    <% end %>
  </div>
</div>

app/views/rooms/index.html.erb
<div class="box">
  <div class="box-header">
    <h1>Salas</h1>
  </div>
  <% if @rooms.any? %>
  <table>
    <thead>
      <tr>
        <th>Evento</th>
        <th>Nome da Sala</th>
        <th>Capacidade Máxima</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @rooms.each do |room| %>
        <tr>
          <td><%= room.event.try(:name) %></td>
          <td><%= room.name %></td>
          <td><%= room.max_capacity %></td>
          <td>
            <%= link_to 'Detalhes', room_path(room), class: "button plain" %>
            <%= link_to 'Editar', edit_room_path(room), class: "button plain" %>
            <%= link_to 'Remover', room_path(room), class: "button plain", method: :delete, data: { confirm: 'Tem Certeza? ' } %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <% else %>
    <div class="box-content">
      <p>Nenhuma sala. <%= link_to 'Adicionar Sala', new_room_path, class: 'button small plain' %></p>
    </div>
  <% end %>

  <%= render partial: 'commons/pagination', locals: { paginated_collection: @rooms } %>
</div>

app/views/rooms/new.html.erb
<div class="box">
  <div class="box-header">
    <h1>Salas</h1>
  </div>
  <div class="box-content">
    <%= form_for(@room) do |f| %>
      <%= render partial: 'form', locals: { f: f } %>
    <% end %>
  </div>
</div>

app/views/rooms/show.html.erb
<div class="grid_6">

  <div class="box">
    <div class="box-header">
      <h1>Evento</h1>
    </div>

    <table>
      <tbody>
        <tr>
          <td>Evento</td>
          <td><strong><%= link_to @room.event.try(:name), event_path(@room.event) %></strong></td>
        </tr>
        <tr>
          <td>Nome da Sala</td>
          <td><%= @room.name %></td>
        </tr>
        <tr>
          <td>Capacidade Máxima</td>
          <td><%= @room.max_capacity %></td>
        </tr>
        <tr>
          <td>Capacidade Mínima</td>
          <td><%= @room.min_capacity %></td>
        </tr>
        <tr>
          <td>Observações</td>
          <td><%= @room.observations || 'Sem Observações.' %></td>
        </tr>
      </tbody>
    </table>

    <div class="action_bar">
      <%= link_to 'Editar', edit_room_path(@room), class: 'button plain' %>
    </div>
  </div>

</div>